# Generated by Django 5.1.6 on 2025-04-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_category',
            field=models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('marketing', 'Marketing'), ('diseño', 'Diseño'), ('finanzas', 'Finanzas'), ('educacion', 'Educación'), ('salud', 'Salud'), ('ingenieria', 'Ingeniería'), ('legal', 'Legal'), ('recursos_humanos', 'Recursos Humanos'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='career_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='values',
            field=models.TextField(blank=True),
        ),
    ]
