# Generated by Django 5.1.6 on 2025-05-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_job_category_alter_profile_career_goals_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='job_category',
            new_name='categoria_trabajo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='career_goals',
            new_name='habilidades',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='interests',
            new_name='intereses',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='experience_level',
            new_name='nivel_experiencia',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='objetivos_profesionales',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_updated',
            new_name='ultima_actualizacion',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='values',
            new_name='valores',
        ),
        migrations.AddField(
            model_name='profile',
            name='certificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='disponibilidad',
            field=models.CharField(blank=True, choices=[('inmediata', 'Inmediata'), ('1_mes', '1 Mes'), ('2_meses', '2 Meses'), ('mas_de_2_meses', 'Más de 2 meses')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='educacion_maxima',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='idiomas_hablados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tipo_trabajo_preferido',
            field=models.CharField(blank=True, choices=[('remoto', 'Remoto'), ('hibrido', 'Híbrido'), ('presencial', 'Presencial')], max_length=100, null=True),
        ),
    ]
