# Generated by Django 5.1.6 on 2025-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_job_category_profile_categoria_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categoria_trabajo',
            field=models.CharField(blank=True, choices=[('tecnologia', 'Tecnología'), ('marketing', 'Marketing'), ('diseño', 'Diseño'), ('finanzas', 'Finanzas'), ('educacion', 'Educación'), ('salud', 'Salud'), ('ingenieria', 'Ingeniería'), ('legal', 'Legal'), ('recursos_humanos', 'Recursos Humanos')], max_length=50),
        ),
    ]
