# Generated by Django 5.1.6 on 2025-04-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=50),
        ),
    ]
