# Generated by Django 5.1.6 on 2025-05-07 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_experience_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='is_active',
            new_name='esta_activa',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='date_posted',
            new_name='fecha_publicacion',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skills_required',
            new_name='habilidades_requeridas',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary_range',
            new_name='rango_salarial',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='requirements',
            new_name='requisitos',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='responsibilities',
            new_name='responsabilidades',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='ubicacion',
        ),
        migrations.RemoveField(
            model_name='job',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='experience_level',
        ),
        migrations.AddField(
            model_name='job',
            name='categoria_trabajo',
            field=models.CharField(choices=[('diseño_grafico', 'Diseño gráfico'), ('ingenieria_informatica', 'Ingeniería informática'), ('marketing_digital', 'Marketing digital'), ('finanzas', 'Finanzas'), ('salud', 'Salud'), ('educacion', 'Educación'), ('administracion', 'Administración'), ('recursos_humanos', 'Recursos humanos'), ('otro', 'Otro')], default='ingenieria_informatica', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='nivel_experiencia',
            field=models.CharField(choices=[('entry', 'Entry'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='entry', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='tipo_empleo',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('medio_tiempo', 'Medio tiempo'), ('contrato', 'Contrato'), ('pasantia', 'Pasantía'), ('remoto', 'Remoto')], default='tiempo_completo', max_length=50),
        ),
    ]
