# Generated by Django 5.1.6 on 2025-05-19 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_categoria_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='categoria_trabajo',
            field=models.CharField(choices=[('diseno_grafico', 'Diseño gráfico'), ('ingenieria_informatica', 'Ingeniería informática'), ('marketing_digital', 'Marketing digital'), ('ingenierias', 'Ingenierias'), ('finanzas', 'Finanzas'), ('salud', 'Salud'), ('educacion', 'Educación'), ('administracion', 'Administración'), ('recursos_humanos', 'Recursos humanos')], default='ingenieria_informatica', max_length=100),
        ),
        migrations.CreateModel(
            name='JobEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_vector', models.BinaryField()),
                ('sentence_embedding', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='jobs.job')),
            ],
        ),
    ]
