# Generated by Django 5.1.6 on 2025-04-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRecommendation',
        ),
    ]
